<?php

namespace App\Models;

use App\Constants\CacheConstant;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Clinic extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = ['name'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::created(function () {
            cache()->forget(CacheConstant::CLINIC);
        });
        static::updated(function () {
            cache()->forget(CacheConstant::CLINIC);
        });
    }
    public function advisors()
    {
        return $this->belongsToMany(Advisor::class,'advisor_clinic');
    }

}
